// AUTOGENERATED by `uv run pixfabrica web gen-typography` — do not edit.
import defaults from './typography.defaults.json' with { type: 'json' }

export const REFERENCE_HEIGHT = 1080 as const

export const FONT_ROLES = ["display_large", "display_medium", "display_small", "title_large", "title_medium", "title_small", "body_large", "body_medium", "body_small", "label_large", "label_medium", "label_small", "mono_large", "mono_medium", "mono_small"] as const
export type FontRole = (typeof FONT_ROLES)[number]

export interface FontSpec {
  family: string
  weight: number
  size: number
  line_height: number
  letter_spacing: number
  color: string
}

export type FontPalette = { [K in FontRole]: FontSpec }

export const FONT_ROLE_GROUPS = {
  display: ["display_large", "display_medium", "display_small"] as const,
  title: ["title_large", "title_medium", "title_small"] as const,
  body: ["body_large", "body_medium", "body_small"] as const,
  label: ["label_large", "label_medium", "label_small"] as const,
  mono: ["mono_large", "mono_medium", "mono_small"] as const,
} as const satisfies Record<string, readonly FontRole[]>

export const DEFAULT_FONT_PALETTE = defaults as FontPalette
