"""Regenerate THIRD_PARTY_NOTICES.md from plugin clip_license metadata."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from pixfabrica_core.catalog import build_catalog_cache
from pixfabrica_core.license_policy import DEFAULT_PLUGIN_LICENSE
from pixfabrica_core.plugins.discovery import discover_plugins

console = Console()

_REPO_ROOT = Path(__file__).resolve().parents[4]
_DEFAULT_OUTPUT = _REPO_ROOT / "THIRD_PARTY_NOTICES.md"

_KNOWN_SOURCES: dict[str, str] = {
    "std-star-dust-gl": "Shadertoy intro shader by Dmitry Andreev (and'2014)",
    "std-cosmic-network-gl": "[Shadertoy lscczl](https://www.shadertoy.com/view/lscczl)",
    "std-singularity-gl": "[Shadertoy 3csSWB](https://www.shadertoy.com/view/3csSWB)",
    "std-ascend-gl": "[Original write-up](https://art.pkh.me/2026-02-22-ascend.htm)",
    "std-water-drops-gl": "[Shadertoy ltffzl](https://www.shadertoy.com/view/ltffzl)",
}

_KNOWN_AUTHORS: dict[str, str] = {
    "std-star-dust-gl": "Dmitry Andreev (and'2014)",
    "std-cosmic-network-gl": "Martijn Steinrucken (BigWings)",
    "std-singularity-gl": "@XorDev",
    "std-ascend-gl": "bµg",
    "std-water-drops-gl": "Martijn Steinrucken",
}


def _is_third_party_license(license_value: str) -> bool:
    if license_value != DEFAULT_PLUGIN_LICENSE:
        return True
    return "-NC-" in license_value


def _relative_repo_path(path: Path) -> str:
    try:
        return path.relative_to(_REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _collect_notice_rows(plugins_dir: Path | None) -> list[dict[str, str]]:
    discovered, _failed = discover_plugins(plugins_dir)
    cache = build_catalog_cache(discovered)
    rows: dict[str, dict[str, str]] = {}

    for item in (*cache.clips, *cache.effects):
        if not _is_third_party_license(item.license):
            continue
        type_id = getattr(item, "clip_type", None) or getattr(item, "effect_type", "")
        if type_id in rows:
            continue
        rel_guess = f"plugins/{item.plugin_id.replace('pixfabrica-', '')}/src"
        file_hint = f"{rel_guess}/.../{type_id.replace('std-', '').replace('-', '_')}.py"
        rows[type_id] = {
            "component": item.description_fallback.split("—")[0].strip()
            or type_id.removeprefix("std-").replace("-", " ").title(),
            "author": _KNOWN_AUTHORS.get(type_id, "See source file"),
            "license": item.license,
            "source": _KNOWN_SOURCES.get(type_id, "See module docstring"),
            "file": file_hint,
        }
    return [rows[key] for key in sorted(rows)]


def _render_markdown(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Third-party notices",
        "",
        "Pixfabrica is licensed under the [MIT License](LICENSE).",
        "That license applies to Pixfabrica-authored code in this repository.",
        "",
        "Some bundled components retain their original licenses.",
        "They are included under those terms and are **not** relicensed as MIT.",
        "Several Shadertoy ports use **Creative Commons Attribution-NonCommercial-ShareAlike**",
        "licenses, which restrict commercial use of those specific components.",
        "",
        "## CC BY-NC-SA and other third-party shader ports",
        "",
        "| Component | Author | License | Source | File |",
        "|-----------|--------|---------|--------|------|",
    ]
    for row in rows:
        lines.append(
            f"| {row['component']} | {row['author']} | {row['license']} | {row['source']} | `{row['file']}` |"
        )
    lines.extend(
        [
            "",
            "When redistributing or commercializing Pixfabrica, review these notices and comply with each component's license.",
            "For NC-licensed shaders, commercial use requires separate permission from the respective authors or replacement of those components.",
            "",
            "_Auto-generated by `uv run pixfabrica plugin gen-notices`. Do not edit by hand._",
            "",
        ]
    )
    return "\n".join(lines)


def gen_notices(
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Output markdown path"),
    ] = None,
    plugins_dir: Annotated[
        Path | None,
        typer.Option("--plugins-dir", help="Plugins root to scan (default: repo plugins/)"),
    ] = None,
) -> None:
    """Write THIRD_PARTY_NOTICES.md from clip_license ClassVars across plugins."""
    out_path = (output or _DEFAULT_OUTPUT).resolve()
    rows = _collect_notice_rows(plugins_dir.resolve() if plugins_dir else None)
    if not rows:
        console.print("[yellow]No third-party licensed clip types found.[/yellow]")
    out_path.write_text(_render_markdown(rows), encoding="utf-8")
    console.print(f"[green]OK[/green] Wrote {out_path} ({len(rows)} component(s))")
