"""Generate web typography defaults and types from pixfabrica_core.theme.typography."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

console = Console()

_MONO_ROLES = frozenset({"mono_large", "mono_medium", "mono_small"})


def gen_typography(
    web_dir: Annotated[
        Path,
        typer.Argument(help="Path to the web/ package root"),
    ] = Path("web"),
) -> None:
    """Write typography.defaults.json and typography.generated.ts from FontPalette."""
    from pixfabrica_core.theme.typography import FontPalette

    web_root = web_dir.resolve()
    lib = web_root / "src" / "lib"
    lib.mkdir(parents=True, exist_ok=True)

    palette = FontPalette()
    roles = list(FontPalette.model_fields.keys())
    defaults = palette.model_dump()

    defaults_path = lib / "typography.defaults.json"
    defaults_path.write_text(json.dumps(defaults, indent=2) + "\n", encoding="utf-8")

    groups = {
        "display": ["display_large", "display_medium", "display_small"],
        "title": ["title_large", "title_medium", "title_small"],
        "body": ["body_large", "body_medium", "body_small"],
        "label": ["label_large", "label_medium", "label_small"],
        "mono": ["mono_large", "mono_medium", "mono_small"],
    }

    ts_path = lib / "typography.generated.ts"
    ts_path.write_text(
        _render_ts(roles=roles, groups=groups, defaults_json=defaults_path.name),
        encoding="utf-8",
    )

    console.print(f"[green]OK[/green] {defaults_path}")
    console.print(f"[green]OK[/green] {ts_path}")


def _render_ts(*, roles: list[str], groups: dict[str, list[str]], defaults_json: str) -> str:
    roles_literal = ", ".join(f'"{r}"' for r in roles)
    group_entries = ",\n  ".join(
        f"{name}: [{', '.join(f'"{r}"' for r in rs)}] as const" for name, rs in groups.items()
    )
    return f"""// AUTOGENERATED by `uv run pixfabrica web gen-typography` — do not edit.
import defaults from './{defaults_json}' with {{ type: 'json' }}

export const REFERENCE_HEIGHT = 1080 as const

export const FONT_ROLES = [{roles_literal}] as const
export type FontRole = (typeof FONT_ROLES)[number]

export interface FontSpec {{
  family: string
  weight: number
  size: number
  line_height: number
  letter_spacing: number
  color: string
}}

export type FontPalette = {{ [K in FontRole]: FontSpec }}

export const FONT_ROLE_GROUPS = {{
  {group_entries},
}} as const satisfies Record<string, readonly FontRole[]>

export const DEFAULT_FONT_PALETTE = defaults as FontPalette
"""
